apiVersion: apps/v1
kind: Deployment
metadata:
  name: caresnap-deployment
  labels:
    app: caresnap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caresnap
  template:
    metadata:
      labels:
        app: caresnap
    spec:
      containers:
      - name: caresnap-container
        image: avasil08/caresnap:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: caresnap-service
spec:
  selector:
    app: caresnap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
Th