apiVersion: v1
kind: Service
metadata:
  name: caresnap-service
  namespace: pschatbot
spec:
  type: ClusterIP
  selector:
    app: caresnap
  ports:
    - name: frontend
      port: 80              # Expose port 80 for Nginx (Frontend)
      targetPort: 80         # Nginx port within the pod
    - name: backend
      port: 5000            # Port for the backend service (update based on your backend setup)
      targetPort: 5000       # Backend service port
