apiVersion: v1
kind: Service
metadata:
  name: caresnap-service
  namespace: pschatbot
spec:
  type: ClusterIP
  selector:
    app: caresnap
  ports:
    - name: frontend
      port: 80              # Expose port 80 for external access
      targetPort: 4200       # Port inside the pod where Nginx is serving the Angular app

